### ISSUE TITLE
source code totally have different look then site

### ISSUE THREAD

**Issue by lucasjinreal** [yaseenmustapha/nextjs13-app#14]
This is runs real:

<img width="1399" alt="截屏2023-12-10 16 06 41" src="https://github.com/yaseenmustapha/nextjs13-app/assets/21303438/4ea6f6d0-5567-42a6-8e04-d427f2b6e16b">

why u open source this?

**Comment by yaseenmustapha** [comment]
The source code is exactly what is deployed on Vercel and on the live site.

**Comment by lucasjinreal** [comment]
I can't reproduce it, the whole style are gone.
